### ISSUE TITLE
Not a issue but a suggestion

### ISSUE THREAD

**Issue by Horst12** [gepruts/QuickSwitch#1]
It would be nice to provide compiled versions for 32bit and 64bit in addition to the ahk source.
Its not importand for me as I have Autohotkey installed (of course)
but others may be interested on QuickSwitch but don't want to install Autohotkey itself.

**Comment by gepruts** [comment]
From now on, releases will be provided in compiled form (32- and 64-bit).
Thank you for your suggestion!
