### ISSUE TITLE
dialog selection not assigned

### ISSUE THREAD

**Issue by RotemBlumberg** [gepruts/QuickSwitch#3]
I encounter an issue with the dialog when selecting "Allow AutoSwitch" or "Never here".
After clicking the dialog disappears but the option is not selected and just reappears on the window focus.
I am on Windows 11.

**Comment by gepruts** [comment]
- Is QuickSwitch in a **writable** folder? (where new files can be created easily)
- Is there a **JumpToFolder.ini** in this folder?
- Can you post the **contents** of your JumpToFolder.ini?

**Comment by gepruts** [comment]
@Rotemblumberg:

is this still an issue?

**Comment by gepruts** [comment]
Solved

**Comment by RotemBlumberg** [comment]
Hello, I apologize for the delay. I was away.

It was previously located at "C:\Program Files\QuickSwitch\QuickSwitch.exe" and ini file was not created.
After your device, I have changed the path to "C:\Users\<Username>\pathTo\QuickSwitch\QuickSwitch.exe" for write permission availability.
Now the ini file is created (it is called: "QuickSwitch.ini" and not "JumpToFolder.ini").
This is its content after selecting "Allow AutoSwitch" in Word save dialog:
[Dialogs]
WINWORD.EXE___Save As=1
But the quick switch does not occur.
I click the other explorer folder and then back to the save dialog, but nothing happens.

Your help is appreciated.
