### ISSUE TITLE
Option for always Auto Switch without prompt

### ISSUE THREAD

**Issue by fenchai23** [gepruts/QuickSwitch#6]
I am sure this is what I would want, many would want as well, add this option to the tray menu (ill try to do this in my free time)

Although not necessary, it is a time saver if people just prefer the script to always auto switch rather than set auto switch to every type of dialogs.

**Comment by gepruts** [comment]
Thanks for the suggestion, fenchai23!
It was already on my To-Do list, so will be implemented in a next version.

**Comment by fenchai23** [comment]
already added this feature on my fork 👌 

https://github.com/fenchai23/QuickSwitch/commit/110095ee07a4e6c5eb90d4fe0abfd42aa58adf16

you can add this to the main branch if you want. I think this is all I want from the app hehe.
